version: 2

builds:
  - main: .
    binary: shs
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

brews:
  - repository:
      owner: gurisugi
      name: homebrew-tap
    homepage: https://github.com/gurisugi/shs
    description: A CLI tool that splits chained shell commands into individual commands

changelog:
  disable: true
